version: '3.8'

services:
  node:
    image: ${COMPOSE_PROJECT_NAME}/node:16-alpine
    build: images/node
    command: /bin/sh -c "npm run start:debug"
    restart: on-failure
    ports:
      - '${HTTP_PORT}:80'
    volumes:
      - ../:/var/www
  minio:
    image: minio/minio:RELEASE.2022-11-10T18-20-21Z.fips
    command: server --console-address :9001 /data
    restart: on-failure
    ports:
      - '${S3_PORT}:9000'
      - '${S3_CONSOLE_PORT}:9001'
    volumes:
      - s3:/data
    environment:
      - MINIO_ACCESS_KEY=${S3_ACCESS_KEY}
      - MINIO_SECRET_KEY=${S3_SECRET_KEY}
volumes:
  s3:
